In [87]:
a = [2, 4, 6, 8]
print(a)

[2, 4, 6, 8]


In [88]:
type(a)

list

In [89]:
import numpy as np
b=np.array(a)
print(b)
type(b)

[2 4 6 8]


numpy.ndarray

In [90]:
b.ndim


1

In [91]:
a = [[2, 4, 6, 8],[2, 4, 6, 8]]
import numpy as np
b=np.array([a])
b.ndim

3

In [92]:
b.shape

(1, 2, 4)

In [93]:
a=[[1,2,3,4,5,6],
   [4,5,6,7,7,8],
   [7,8,9,0,1,3],
   [1,3,5,7,9,11]]



In [94]:
a

[[1, 2, 3, 4, 5, 6],
 [4, 5, 6, 7, 7, 8],
 [7, 8, 9, 0, 1, 3],
 [1, 3, 5, 7, 9, 11]]

In [95]:
a=[[1,2,3,4,5,6],
   [4,5,6,7,7,8],
   [7,8,9,0,1,3],
   [1,3,5,7,9,11]]
b = np.array(a)
b.ndim

2

In [96]:
b.shape

(4, 6)

In [97]:
a=[[[[1,2,3,4,5,6],
   [4,5,6,7,7,8],
   [7,8,9,0,1,3],
   [1,3,5,7,9,11]]]]
b = np.array([a])
b.ndim

5

In [98]:
b.shape

(1, 1, 1, 4, 6)

In [99]:
c=[[2,3,4,5],[6,7,8,9]]
b = np.array([c])
print(b)


[[[2 3 4 5]
  [6 7 8 9]]]


In [100]:
b.reshape(4,2)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [101]:
b=np.arange(5,100)
print(b)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52
 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76
 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [103]:
grades = np.array([[87, 96, 70], [100, 87, 90], [94, 77, 90], [100, 81, 82]])


In [105]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [107]:
grades.max()

100

In [117]:
a=[[[[1,2,3,4,5,6],
   [4,5,6,7,7,8],
   [7,8,9,0,1,3],
   [1,3,5,7,9,11]]]]

print(a[3:4,4:5])

TypeError: list indices must be integers or slices, not tuple

In [113]:
a = [[[1,2,3,4,5,6],
   [4,5,6,7,7,8],
   [7,8,9,0,1,3],
   [1,3,5,7,9,11]]]]

print(a[0][0][3:][4:])

SyntaxError: unmatched ']' (<ipython-input-113-8728ad6adf85>, line 4)